trigger:
- main
- pipeline-dev
- stock-news

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '9.0.200'
  projectPath: 'TradingApp/TradingApp.csproj'
  testProjects: 'TradingApp.Tests/TradingApp.Tests.csproj' 
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- checkout: self
  fetchDepth: 0  # Fetch full history
  persistCredentials: true

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '**/*.sln'

# Prepare sonarcloud analysis
- task: SonarCloudPrepare@3
  displayName: 'Prepare SonarCloud analysis'
  inputs:
    SonarCloud: 'SonarQube-Connection'
    organization: 'rhys-0'
    scannerMode: 'dotnet'
    projectKey: 'Rhys-0_Trading-Platform'
    extraProperties: |
      sonar.test.inclusions=**/TradingApp.Tests/**/*.cs

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: '$(testProjects)'
    arguments: >
      --configuration $(buildConfiguration)
      --no-build
      --collect:"XPlat Code Coverage"
      --results-directory $(Agent.TempDirectory)
    publishTestResults: true

- task: SonarCloudAnalyze@3
  displayName: 'Run SonarCloud analysis'
