trigger:
- main
- pipeline-dev
- database-dev
- stock-news
- order-page
- stockpage
- shilpi-dev
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '9.0.200'
  projectPath: 'TradingApp/TradingApp.csproj'
  testProjects: 'TradingApp.Tests/TradingApp.Tests.csproj' 
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'
  runSettingsFile: '$(Build.SourcesDirectory)/coverlet.runsettings'

steps:
- checkout: self
  fetchDepth: 0
  persistCredentials: true

- script: |
    sudo systemctl start docker
    sudo usermod -aG docker $USER
    sudo chmod 666 /var/run/docker.sock
    sudo docker pull postgres:15-alpine
    docker --version
    docker info
  displayName: 'Start Docker and Download Postgres Image'

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests with Coverage'
  inputs:
    command: 'test'
    projects: '$(testProjects)'
    arguments: >
      --configuration $(buildConfiguration)
      --no-build
      --settings $(runSettingsFile)
      --logger "console;verbosity=normal"
      --collect:"XPlat Code Coverage"
  env:
    DOCKER_HOST: unix:///var/run/docker.sock

- task: PublishCodeCoverageResults@2
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: 'OpenCover'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.opencover.xml'
    reportDirectory: '$(Agent.TempDirectory)'
